### ISSUE TITLE
该项目下执行 ./vendor/bin/phpunit 报错

### ISSUE THREAD

**Issue by becage** [summerblue/larabbs#28]
自定义的函数影响到单元测试
```
git clone https://github.com/summerblue/larabbs.git
cd larabbs/
cp .env.example .env
composer install
php artisan key:generate
php artisan migrate:refresh --seed
./vendor/bin/phpunit
```
![image](https://user-images.githubusercontent.com/41765271/51815760-191ed780-22fe-11e9-9b3f-240b3306302d.png)

**Comment by liyu001989** [comment]
切换到 api 分支，或者修改  `bootstrap/app.php` 将 require 改成 require_once。

课程已经补充了
