### ISSUE TITLE
sudosu::user-selector 这个视图找不到

### ISSUE THREAD

**Issue by dongm2ez** [summerblue/larabbs#9]
/larabbs/resources/views/layouts/app.blade.php  文件中

**Comment by wsmsn** [comment]
在配置文件config/sudosu.php的allowed_tld中添加你的域名后缀
```php
// 允许使用的顶级域名
    'allowed_tlds' => ['dev', 'local', 'app', 'test', 'net'],
```

**Comment by ZoeSj** [comment]
我也遇到了这个，按照你说的，添加了域名，但是依然报错

**Comment by yyqyangyongqiang** [comment]
如果为本地测试，可使用   'allowed_tlds' => ['localhost', 'local', 'test'],
